### ISSUE TITLE
手順書の修正

### ISSUE THREAD

**Issue by ghost** [harunobukameda/Amazon-Redshift-Spectrum-AWS-Glue-Amazon-Athena-Amazon-S3-Select#1]
[datalake-handson-text_20201115.pdf](https://github.com/harunobukameda/Amazon-Redshift-Spectrum-AWS-Glue-Amazon-Athena-Amazon-S3-Select/files/5542075/datalake-handson-text_20201115.pdf)
[datalake-handson-text_20201115.docx](https://github.com/harunobukameda/Amazon-Redshift-Spectrum-AWS-Glue-Amazon-Athena-Amazon-S3-Select/files/5542076/datalake-handson-text_20201115.docx)

@harunobukameda 
いくつか追記やキャプチャの差し替えが必要だったので、ドキュメントを最新化しました。
差し替え後のものをAttachしたので確認してみてください。

> P.7 S3のコンソールキャプチャを変更
> 
> P.８ 注釈追加
> 注：誤って「既存のリソース仕様(リソースをインポート)」を選択した場合、「リソースのインポートではサポートされていません」というエラーが出力されます。
> 
> P.13 次の画面に対し補足を追記
> 次の画面(Specify crawler source type)もそのまま [次へ] をクリックします。
> 
> P.18 ドライラン実行に発生した事象に対する回避方法を追記
> 5.	クエリエディタで下記 SQL を実行します。「クエリの実行」ボタンがクリック出来ない場合はブラウザをリロードしてみてください。
> 
> p.19 S3のコンソールキャプチャを変更
> 
> P.19 新しいS3コンソールにあわせて文言修正
> 4.	[アクション] → [S3 Selectを使用したクエリ]をクリックします
> 
> P.19 新しいS3コンソールにあわせて文言修正
> 6.	SQLを入力し、[SQLの実行クエリ]をクリックします。
> 
> P.23 Redshiftコンソールにあわせて文言修正
> 3.	[サブネットグループ] 項目より、 [サブネットグループの管理]をクリックします。クラスターサブネットグループ画面より、右上の[クラスターサブネットグループの作成] をクリックします。
> 
> P.25 選択項目を明記
> 3.	左ペインの[select schema]より[information_schema]を選択し、にテーブル一覧が表示されれば、ログイン成功です。
> 
> P.29 Redshiftコンソールにあわせて文言修正　および　キャプチャを追加
> クラスター一覧画面で [クラスターステータス] が [Available] になるまで待ちます。変更中が出ている間はまだ適応作業中ですので数分間待ちます。
> 
> P.30 5.2.3-5のSQLがページ跨ぎになっているのでページ送りして１つに集約
> 
> P.34 S3パスを明記
> 7.	出力先(S3バケット名/export)のバケット、パスを確認します。ファイルを選択し、「S3 Select」タブを選択します。
>

**Comment by harunobukameda** [comment]
Cleared
